CREATE TABLE pessoa (
    idPessoa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomePessoa VARCHAR2(50) NOT NULL,
    cpfPessoa VARCHAR2(30) UNIQUE,
    emailPessoa VARCHAR2(50) NOT NULL,
    telPessoa VARCHAR2(30) NOT NULL
);

CREATE TABLE endereco (
    idEnd NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idPessoa NUMBER NOT NULL,
    rua VARCHAR2(30) NOT NULL,
    numero VARCHAR2(30) NOT NULL,
    bairro VARCHAR2(30) NOT NULL,
    cidade VARCHAR2(30) NOT NULL,
    estado VARCHAR2(30) NOT NULL,
    cep VARCHAR2(30) NOT NULL,
    FOREIGN KEY (idPessoa) REFERENCES pessoa(idPessoa)
);

CREATE TABLE equipamento (
    idEqpt NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idResponsavel NUMBER,
    descricao VARCHAR2(30) NOT NULL,
    categoria VARCHAR2(30) NOT NULL,
    marca VARCHAR2(20) NOT NULL,
    modelo VARCHAR2(10) NOT NULL,
    sn VARCHAR2(50) NOT NULL,
    status VARCHAR2(30) DEFAULT 'Disponível'
    CONSTRAINT fkResponsavel FOREIGN KEY (idResponsavel) REFERENCES pessoa(idPessoa)
);

CREATE TABLE movimentacoes (
    idMov NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idEqpt NUMBER NOT NULL,
    idPessoa NUMBER NOT NULL,
    dataMov DATE DEFAULT SYSDATE,
    tipoMov VARCHAR2(30) NOT NULL,
    FOREIGN KEY (idEqpt) REFERENCES equipamento(idEqpt),
    FOREIGN KEY (idPessoa) REFERENCES pessoa(idPessoa)
)

-- Tuning é um processo de otimização que visa melhorar o desempenho de uma infraestrutura de dados.

-- Ajuste na tabela 'pessoa': tamanho do campo cpfPessoa
ALTER TABLE pessoa MODIFY cpfPessoa VARCHAR2(11);
ALTER TABLE pessoa ADD CONSTRAINT chk_cpf CHECK(LENGTH(cpfPessoa)=11);

-- Ajuste na tabela 'endereco': tamanho do campo cep
ALTER TABLE endereco MODIFY cep VARCHAR2(8);
ALTER TABLE endereco ADD CONSTRAINT chk_cep CHECK(LENGTH(cep)=8);

